import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import { LandingSection } from "../components/landing";
import Products from "../components/products";
import { Features } from "@/Components/features";
import data from "../products.json"
import { Footer } from "@/Components/footer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
     <Navbar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingSection />
      <Products />
      <Features />
    <Footer /> 
    </>
    
  );
}
